// Generated by CoffeeScript 2.3.1
(function() {
  // https://bl.ocks.org/gordlea/27370d1eea8464b04538e6d8ced39e89
  var lineChart;

  window.lineChart = lineChart = class lineChart {
    constructor() {
      var that;
      this.margin = {
        top: 50,
        right: 50,
        bottom: 50,
        left: 50
      };
      this.jsondata = this.getJSONdata();
      this.width = window.innerWidth - this.margin.left - this.margin.right; //window's inner width
      this.height = window.innerHeight - this.margin.top - this.margin.bottom; //window's inner width
      this.parseDate = d3.timeParse("%Y");
      
      // X Scale
      that = this;
      this.xScale = d3.scaleTime().domain(d3.extent(this.jsondata, function(d) {
        return d.year = that.parseDate(d.year); //input
      })).range([
        0,
        this.width //output
      ]);
      
      // Y Scale  
      this.yScale = d3.scaleLinear().domain([
        0,
        d3.max(this.jsondata,
        function(d) {
          return d.count;
        }) + 1000 //input
      ]).range([
        this.height,
        0 //output
      ]);
      
      // Add Tool tip Div to chart
      this.toolTipDiv = d3.select('.drawBoard').append('div').attr('class', 'toolTip').style('opacity', 0);
      
      //1. attach SVG to body
      this.svg = d3.select(".drawBoard").append("svg").attr("class", "lineChart").attr("height", this.height + this.margin.top + this.margin.bottom).attr("width", this.width + this.margin.left + this.margin.right).append("g").attr("class", "gContainer").attr("transform", "translate( " + this.margin.left + " , " + this.margin.top + ")");
    }

    init() {
      this.addAxes();
      this.drawHorizontalGridLines(this.width);
      this.connectPoints();
      return this.plotPoints();
    }

    getJSONdata() {
      var dataArray;
      dataArray = [];
      $.ajax({
        type: "GET",
        async: false,
        url: "./lineChart.json",
        data: {
          get_param: 'value'
        },
        dataType: "json",
        success: function(data) {
          return dataArray = data;
        }
      });
      return dataArray;
    }

    addAxes() {
      
      // 2. Call the x axis in a group tag	
      this.svg.append("g").attr("class", "xAxis").attr("transform", "translate( 0, " + this.height + ")").call(d3.axisBottom(this.xScale)); // Create an axis component with d3.axisBottom
      
      //3. Call the y axis in a group tag		
      return this.svg.append("g").attr("class", "yAxis").call(d3.axisLeft(this.yScale)); // Create an axis component with d3.axisLeft	
    }

    connectPoints() {
      var that;
      that = this;
      //4.d3's line generator
      this.line = d3.line().x(function(d) {
        return that.xScale(d.year); //set the x co-ordinates values for the line generator
      }).y(function(d) {
        return that.yScale(d.count); //set the y co-ordinates values for the line generator 
      }).curve(d3.curveMonotoneX); // apply smoothing to the line
      
      //5. Append Path , bind the data and call the line generator
      return this.svg.append("path").datum(this.jsondata).attr("class", "line").attr("d", this.line); //Bind Data to line //calls the line generator
    }

    plotPoints() {
      var that;
      //6. Append a circle for each datapoint				
      that = this;
      return this.svg.selectAll(".dot").data(this.jsondata).enter().append("circle").attr("class", "dot").attr("cx", function(d) {
        return that.xScale(d.year);
      }).attr("cy", function(d) {
        return that.yScale(d.count);
      }).attr("r", 5).style("fill", "	#34738f").attr("stroke", "#fff").on("mouseover", function(d) {
        var boxHeight, boxWidth, leftPosition, topPosition;
        d3.select(this).attr("r", 8).style("fill", function(d) {
          return "#fff";
        }).attr("stroke", '#34738f').attr("stroke-width", 5);
        leftPosition = $(this).attr("cx");
        topPosition = $(this).attr("cy");
        boxWidth = $(".drawBoard").width();
        boxHeight = $(".drawBoard").height();
        //when tooltip lies on right edge , pull it in
        if ((boxWidth - leftPosition) < 100) {
          leftPosition = leftPosition - (boxWidth - leftPosition);
        }
        
        //when point is on x=0 ; i.e. y-axis	
        if (parseInt(leftPosition) === 0) {
          leftPosition = 25;
        }
        //when point is at top of chart
        if (parseInt(topPosition) < 25) {
          topPosition = 60;
        }
        that.toolTipDiv.transition().duration(200).style('opacity', 0.9);
        return that.toolTipDiv.html("Year : " + d.year.getFullYear() + "<br>" + "Count : " + d.count).style("left", leftPosition + "px").style("top", topPosition + "px");
      }).on("mouseout", function(d) {
        d3.select(this).attr("r", 5).style("fill", "#34738f").attr("stroke", '#fff').attr("stroke-width", 1);
        return that.toolTipDiv.transition().duration(500).style('opacity', 0);
      });
    }

    drawHorizontalGridLines(width) {
      //7. To add horizontal lines on graph
      this.svg.append("g").attr("class", "grid");
      //add lines to graph parallel to x-axis
      return this.svg.select(".grid").call(d3.axisLeft(this.yScale).ticks(10).tickSize(-this.width).tickFormat(''));
    }

  };

  $(document).ready(function() {
    var chart;
    chart = new lineChart();
    return chart.init();
  });

}).call(this);
